name: Checks

on:
  pull_request:
  push:
      branches:
        - main

jobs:
  checks:
    name: Run checks
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Tools
        uses: actions/checkout@v4
      - name: Checkout AI Lab
        uses: actions/checkout@v4
        with:
          repository: containers/podman-desktop-extension-ai-lab
          path: podman-desktop-extension-ai-lab
      - name: Link podman-desktop-extension-ai-lab in forks
        # Location of the podman-desktop-extension-ai-lab repo must match the location in my local machine
        # See package.json
        run: |
          mkdir -p ../../forks
          ln -s $(pwd)/podman-desktop-extension-ai-lab ../../forks/podman-desktop-extension-ai-lab
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Test
        run: pnpm test
