name: Checks

on:
  pull_request:
  push:
      branches:
        - main

jobs:
  if: false # disables until we implement checkout of AI Lab
  checks:
    name: Run checks
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Test
        run: pnpm test
